server {
    listen 80;
    listen [::]:80;

    server_name hakaa.publicvm.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name hakaa.publicvm.com;

    ssl_certificate /etc/letsencrypt/live/hakaa.publicvm.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hakaa.publicvm.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 20M;

    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $fastapi_upstream fastapi:8000;

    location ~ ^/api/v1/(data/(upload|process)|nlp/index/(push|info))/ {
        auth_basic "Mini-RAG Admin";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://$fastapi_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 7200s;
        proxy_read_timeout 7200s;
    }
    location = /admin {
    return 301 /admin/;
    }

    location ^~ /admin/ {
        auth_basic "Mini-RAG Admin";
        auth_basic_user_file /etc/nginx/.htpasswd;

        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://$fastapi_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 7200s;
        proxy_read_timeout 7200s;
    }
}