APP_NAME="mini-RAG"
APP_VERSION="0.1"
OPEN_API_KEY=""

#============================== FILE CONFIG ==============================
FILE_ALLOWED_TYPES=["text/plain", "application/pdf"]
FILE_MAX_SIZE=15
FILE_DEFAULT_CHUNK_SIZE=512000
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres751482
POSTGRES_HOST=pgvector
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE=minirag


#============================== LLM CONFIG ===============================
GENERATION_BACKEND="OPENAI"
EMBEDDING_BACKEND="NEMOTRON"

OPENAI_API_KEY="NEW_ROTATED_OPENROUTER_KEY"
OPENAI_API_URL="https://openrouter.ai/api/v1"

GENERATION_MODEL_ID="openai/gpt-oss-20b:free"
EMBEDDING_MODEL_ID="nvidia/nemotron-3-embed-1b:free"
EMBEDDING_MODEL_SIZE=1024

INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=2000
GENERATION_DEFAULT_TEMPRATURE=0.1

#============================== VECTOR DB CONFIG =========================
VECTOR_DB_BACKEND_LITERAL=["QDRANT", "PGVECTOR"]
VECTOR_DB_BACKEND="PGVECTOR"
VECTOR_DB_PATH="qdrant_db"
VECTOR_DB_DISTANCE_METHOD="cosine"
VECTOR_DB_INDEX_THRESHOLD = 100

#============================== TEMPLATE CONFIG ==========================
DEFAULT_LANG="ar"
PRIMARY_LANG="ar"
